### ISSUE TITLE
License

### ISSUE THREAD

**Issue by comradekingu** [lavafeld/magma-guide#13]
https://github.com/lavafeld/magma-guide
>All content of the magma guide (unless otherwise mentioned) is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (CC BY-SA 4.0).

https://magma.lavafeld.org
>Creative Commons Attribution **Non Commercial** 4.0 International

Seems to cover everything? Which one is it?

**Comment by anadahz** [comment]
@comradekingu Thank you for reporting this, it the `CC-BY-SA-4.0` license.

Fixed in https://github.com/lavafeld/magma-guide/commit/c5ff62f7c9d3c99153f977ccccf44b0e3b9c893e .
